---
title: "作业二"
author: "mawei"
date: '2020-12-25'
slug: 作业二
categories: []
tags: []
---

# - **球棍模型**

```{r}
library(rgl)

x = c(0, 0, 1)
y = c(0, 1, 3)
z = c(0, 2, 2)
plot3d(
  x,
  y,
  z,
  type = "s",
  xlab = "",
  ylab = "",
  zlab = "",
  box = FALSE,
  axes = F,
  radius = c(0.25, 0.3, 0.25),
  col = c("blue", "white", "blue")
)
ind = c(2, 1, 2, 3)
lines3d(x[ind], y[ind], z[ind], lwd = 2)


x = c(0, 0, 1)
y = c(0, 1, 3)
z = c(0, 2, 2)
plot3d(
  x,
  y,
  z,
  type = "s",
  xlab = "",
  ylab = "",
  zlab = "",
  box = FALSE,
  axes = F,
  radius = rep(0.3,3),
  col = rep("white", 3)
)
ind = c(2, 1, 2, 3)
lines3d(x[ind], y[ind], z[ind], lwd = 2)
```


# - **表调整**

## 原始数据

```{r}
library(tibble)
library(magrittr)
library(tidyverse)
td1 <- tribble(
  ~country, ~year, ~cases, ~population,
  "Afghanistan",  1999,   745,  19987071,
  "Afghanistan",  2000,  2666,  20595360,
  "Brazil",       1999, 37737, 172006362,
  "Brazil",       2000, 80488, 174504898,
  "China",        1999,212258,1272915272,
  "China",        2000,213766,1280428583
)
td3 <- td1 %>% transmute(country = country, year = year, rate = paste0(as.character(cases), "/", as.character(population)))
td4_1 <- td1[, 1:3] %>% spread(key = "year", value = "cases")
td4_2 <- td1[, c(1, 2, 4)] %>% spread(key = "year", value = "population")
td4 <- merge(td4_1, td4_2, by = "country")
names(td4) <- c("country", "cases_1999", "cases_2000", "population_1999", "population_2000")
```

## 表3转为表1

```{r}
newcol = matrix(unlist(strsplit(td3$rate, '/')), ncol = 2, byrow = T)
td3$cases = newcol[, 1]
td3$population = newcol[, 2]
td3 = td3[, -3]
knitr::kable(td3)
```

## 表4转为表1

```{r}
data1=td4[,c(1,2,4)]
data2=td4[,c(1,3,5)]
colnames(data1)=c('country','cases','population')
colnames(data2)=c('country','cases','population')
td4=rbind(data1,data2)
td4$year=rep(c(1999,2000),1,each=3)
knitr::kable(td4)
```
